### ISSUE TITLE
propose and discuss "index.md" solution for resolvable IRIs

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/glossary#56]
**Problem**

Current glossary IRIs (the technical term for the glossary term URLs) are like this: `https://glossary.vhp4safety.nl/#VHP0000005`

But the glossary landing page is the `README.md` and not the `glossary.md`.

**Solution**

I propose to rename the `glossary.md` to `index.md`.

Advantages:

* glossary IRI resolve (read: clicking them will actually show the term in the glossary)

Disadvantage:

* the `README.md` content is no longer visible. But we can link to this page from the new `index.md`.

**What needs to be done**

1. rename the `glossary.md` to `index.md`
2. add `@id="VHP000xxxx"` attributes to the ontology term `<td>` HTML elements

If you like this proposal, add a "thumbs up". If you have a better idea, use a "thumbs down" and leave a better solution in the comment of this issue.

**Comment by marvinm2** [comment]
I think it is a great idea! This can then be used then for e.g. service annotation/applicability/purpose/origin/etc that directly would link to the description etc. If other vocabularies/ontologies would not fit

**Comment by ozancinar** [comment]
I agree with the idea, we can try it. When the user goes to `glossary.vhp4safety.nl/`, I think they already land on the page provided by `glossary.md`. The `README.md` file is the landing page on the repository, and I suspect users will frequently visit the repository rather than the webpage. So, it may not be a huge disadvantage if I am not missing something. 

Another issue I've been thinking for some time is using a numerical order in the term IRIs. They are not much self explanatory, so maybe we can use another method for IRIs. I was thinking something like using the first couple of letters in every word in the term separated by an underscore. For example, we can use `ben_mar_dos` for the term "Bench mark dose". I am not sure if this is feasible, that is if the terms are completely mutually exhaustive if we use such a method. On top of this, I am not sure if this is an important issue but I just wanted to raise it.

**Comment by egonw** [comment]
> They are not much self explanatory, so maybe we can use another method for IRIs

There is not clear consensus (but quite persistent in the OBO Foundry community), but there is a good reason to do this. They are meant to be not explanatory: 

1. any language like identifier is language specific and therefore less inclusive
2. labels change and then acronyms in the IDS can start become even more confusing
3. deprecation is harder: if the definition changes, the ID has to change too. with acronyms you can variants then, like `ben_mar_dos` en `bench_mar_dos` (or something like that), which is also not helping

**Comment by egonw** [comment]
Completed.
